version: '3.8'
services:
  app:
    image: devops-frontend-test
    build:
      context: ./
      target: dev
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "4000:3000"
